### ISSUE TITLE
Items not working correctly

### ISSUE THREAD

**Issue by Apolo-sys** [thelindat/linden_inventory#173]
**Describe the bug**
client part of items its not workingg (add status, anim, prop, usetime and event)

**To Reproduce**
Two options to reproduce:

1: Try to give you default item like (cola) or (burger),
when you try to eat or drink its not working fine the (Animation, event, prop) and doesn't add the status

2: Try to add yourself an item with prop, anim, status and more..
You will see that none of them will work

**Expected behavior**
All things in CLIENT of shared/items.lua working fine

**Additional context**
I checked the code and i think you are using data.status or data.anim instead of data.client.status or data.status.anim

👍

**Comment by thelindat** [comment]
> I checked the code and i think you are using data.status or data.anim instead of data.client.status or data.status.anim

`local data = Items[item.name] and Items[item.name].client`
Thus data.status is equal to Items[item.name].client.status

> 1: Try to give you default item like (cola) or (burger),
> when you try to eat or drink its not working fine the (Animation, event, prop) and doesn't add the status
>
> 2: Try to add yourself an item with prop, anim, status and more..
> You will see that none of them will work

![image](https://user-images.githubusercontent.com/65407488/125180278-907d2300-e23b-11eb-90e5-ea07359965ee.png)

Go remove anything registering the item with ESX since that will overwrite the inventory items.

**Comment by Apolo-sys** [comment]
Thx u, i see rn im overwriting the use with ESX.
