### ISSUE TITLE
identification

### ISSUE THREAD

**Issue by VojtaNN** [thelindat/linden_inventory#62]
Try to add, when a player creates a character he gets an item "identification". And please add weapon licence item with ownership information, which will be added to the inventory when you purchase the license.

**Comment by Ruqen** [comment]
OK, here's what I'm getting.

When a player creates a character, they will get an item named "ID Card" which has his name, gender etc. on it.

Same goes for weapon licenses. Am I right?

**Comment by NiftyLife** [comment]
Simply add xPlayer.addInventoryItem('identification', 1) to your character creator right when the creator ends and the players spawns with its crated char.

**Comment by thelindat** [comment]
As written above. The support is already there for it, but there's no check for a new character in this resource because people use different resources with different outcomes.

If you use ESX Identity make sure you give yourself the item after completing registration and setting xPlayer variables for name, dob, etc.


I'm not doing physical licenses.
