### ISSUE TITLE
cant create a trunk and put items inside

### ISSUE THREAD

**Issue by maxcamorra** [thelindat/linden_inventory#68]
**Describe the bug**
mysql error

**To Reproduce**
1. open trunk
2. put item inside
3. close trunk

**Expected behavior**
trunk should be created and useable

**Screenshots**
![image](https://user-images.githubusercontent.com/78707245/118189452-177f6c00-b442-11eb-99c4-2147d62085a0.png)

**Comment by thelindat** [comment]
3,750 rows in my linden_inventory table, not once has that occurred. The unique index is tied to both plate and identifier, and a query runs to check if the row already exists (update if it does, otherwise insert).

Issues that cannot be reproduced cannot be fixed; and you seem to have a lot of unique issues occurring.
